// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GIR_Capstone.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206100832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Corporate", b =>
                {
                    b.Property<int>("StructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StructureId"));

                    b.Property<string>("MNEName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XMLSubmissionId")
                        .HasColumnType("int");

                    b.HasKey("StructureId");

                    b.ToTable("Corporates");
                });
#pragma warning restore 612, 618
        }
    }
}
